# Generated by Django 4.1.7 on 2023-03-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'LIVE'), (2, 'PENDING'), (3, 'ARCHIVED')], default=2)),
            ],
            options={
                'ordering': ['launch_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'SURVEY'), (2, 'DISCUSSION'), (3, 'DIARY')], null=True)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasktileapp.tile')),
            ],
        ),
    ]
