# Generated by Django 4.1.7 on 2023-03-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='tasktileapp.tile'),
        ),
    ]
