# Generated by Django 4.1.7 on 2023-03-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktileapp', '0002_alter_task_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Survey'), (2, 'Discussion'), (3, 'Diary')], null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Pending'), (3, 'Archived')], default=2),
        ),
    ]
