# Generated by Django 4.1.7 on 2023-03-21 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktileapp', '0003_alter_task_type_alter_tile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
